export const rolesData = [
  {
    name: 'super_admin',
    description: 'Administrador con acceso completo al sistema',
    permissions: [
      'employees:create',
      'employees:read',
      'employees:update',
      'employees:delete',
      'employees:export',
      'payroll:create',
      'payroll:read',
      'payroll:update',
      'payroll:delete',
      'payroll:approve',
      'payroll:export',
      'reports:read',
      'reports:export',
      'reports:advanced',
      'departments:create',
      'departments:read',
      'departments:update',
      'departments:delete',
      'documents:upload',
      'documents:read',
      'documents:delete',
      'admin:access',
      'admin:users',
      'admin:roles',
      'admin:system',
    ],
  },
  {
    name: 'hr_manager',
    description: 'Manager de Recursos Humanos',
    permissions: [
      'employees:create',
      'employees:read',
      'employees:update',
      'employees:export',
      'payroll:create',
      'payroll:read',
      'payroll:update',
      'payroll:approve',
      'payroll:export',
      'reports:read',
      'reports:export',
      'reports:advanced',
      'departments:read',
      'departments:update',
      'documents:upload',
      'documents:read',
      'documents:delete',
    ],
  },
  {
    name: 'payroll_specialist',
    description: 'Especialista en Nóminas',
    permissions: [
      'employees:read',
      'payroll:create',
      'payroll:read',
      'payroll:update',
      'payroll:export',
      'reports:read',
      'reports:export',
      'departments:read',
      'documents:read',
    ],
  },
  {
    name: 'employee',
    description: 'Empleado regular',
    permissions: [
      'employees:read', // Solo su propia información
      'documents:read', // Solo sus propios documentos
      'reports:read', // Solo reportes básicos
    ],
  },
  {
    name: 'viewer',
    description: 'Solo lectura',
    permissions: ['employees:read', 'departments:read', 'reports:read'],
  },
];
